analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    always_put_required_named_parameters_first: error
    avoid_relative_lib_imports: error
    missing_required_param: error
    no_duplicate_case_values: error
    prefer_const_constructors: error
  exclude:
    - lib/generated_plugin_registrant.dart
    - lib/**.g.dart

linter:
  rules:
    - avoid_private_typedef_functions
    - avoid_setters_without_getters
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - constant_identifier_names
    - control_flow_in_finally
    - directives_ordering
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - lines_longer_than_80_chars
    - non_constant_identifier_names
    - one_member_abstracts
    - package_names
    - package_prefixed_library_names
    - prefer_collection_literals
    - prefer_const_constructors
    - prefer_final_locals
    - prefer_function_declarations_over_variables
    - prefer_if_elements_to_conditional_expressions
    - prefer_interpolation_to_compose_strings
    - prefer_null_aware_operators
    - prefer_typing_uninitialized_variables
    - test_types_in_equals
    - type_annotate_public_apis
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_parenthesis
    - unnecessary_statements
    - use_to_and_as_if_applicable
    # Effective Dart Rules
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters
    - avoid_relative_lib_imports
    - avoid_return_types_on_setters
    - avoid_returning_this
    - avoid_types_on_closure_parameters
    - camel_case_extensions
    - curly_braces_in_flow_control_structures
    - file_names
    - library_names
    - library_prefixes
    - omit_local_variable_types
    - prefer_adjacent_string_concatenation
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_generic_function_type_aliases
    - prefer_initializing_formals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_mixin
    - prefer_relative_imports
    - slash_for_doc_comments
    - type_init_formals
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_this
    - use_setters_to_change_properties
